spring.application.name=speechmood

spring.datasource.url=jdbc:postgresql://localhost:5432/speechmood_db
spring.datasource.username=postgres
spring.datasource.password=Caratov12

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

logging.level.org.springframework.security=TRACE