CREATE TABLE IF NOT EXISTS users (
    id bigint generated by default as identity,
    username varchar(255) not null unique,
    password varchar(255) not null,
    primary key (id)
    );

CREATE TABLE IF NOT EXISTS chats (
    id bigint generated by default as identity,
    is_group_chat boolean not null,
    title varchar(255),
    primary key (id)
    );

CREATE TABLE IF NOT EXISTS emotion_reports (
    id bigint generated by default as identity,
    accuracy float(53),
    analyzed_at timestamp(6),
    audio_file_url varchar(255),
    emotion varchar(255),
    user_id bigint not null,
    primary key (id),
    constraint FK_emotion_user foreign key (user_id) references users(id)
    );

CREATE TABLE IF NOT EXISTS chat_messages (
    id bigint generated by default as identity,
    content TEXT,
    sent_at timestamp(6),
    chat_id bigint not null,
    report_id bigint,
    sender_id bigint not null,
    primary key (id),
    constraint FK_msg_chat foreign key (chat_id) references chats(id),
    constraint FK_msg_report foreign key (report_id) references emotion_reports(id),
    constraint FK_msg_sender foreign key (sender_id) references users(id)
    );

CREATE TABLE IF NOT EXISTS chat_participants (
    chat_id bigint not null,
    user_id bigint not null,
    primary key (chat_id, user_id),
    constraint FK_part_chat foreign key (chat_id) references chats(id),
    constraint FK_part_user foreign key (user_id) references users(id)
    );

CREATE TABLE IF NOT EXISTS posts (
    id bigint generated by default as identity,
    content varchar(2000) not null,
    created_at timestamp(6) not null,
    author_id bigint not null,
    primary key (id),
    constraint FK_post_author foreign key (author_id) references users(id)
    );

CREATE TABLE IF NOT EXISTS post_comments (
    id bigint generated by default as identity,
    content varchar(1000) not null,
    created_at timestamp(6) not null,
    author_id bigint not null,
    post_id bigint,
    primary key (id),
    constraint FK_comment_author foreign key (author_id) references users(id),
    constraint FK_comment_post foreign key (post_id) references posts(id)
    );

CREATE TABLE IF NOT EXISTS post_likes (
    id bigint generated by default as identity,
    created_at timestamp(6) not null,
    post_id bigint not null,
    user_id bigint not null,
    primary key (id),
    constraint FK_like_post foreign key (post_id) references posts(id),
    constraint FK_like_user foreign key (user_id) references users(id)
    );

CREATE TABLE IF NOT EXISTS blacklisted_tokens (
    id bigint generated by default as identity,
    token varchar(500) not null unique,
    expiry_date timestamp(6),
    primary key (id)
    );